# Generated by Django 3.1.8 on 2021-11-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('nid', models.CharField(max_length=1000)),
            ],
        ),
    ]
