# Generated by Django 3.1.8 on 2021-11-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctor_veri'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('day', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=1000)),
            ],
        ),
    ]
