# Generated by Django 3.1.8 on 2021-11-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='schedule',
        ),
    ]
