# Generated by Django 3.1.8 on 2021-11-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211108_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('doctor', models.CharField(max_length=1000)),
                ('app_id', models.IntegerField()),
            ],
        ),
    ]
